theme = "archie"

baseURL = 'https://mingzhongshui.github.io/'
# locale = 'en-us'
languageCode = 'en-us'      # 注意是 languageCode，不是 locale
title = '命中水、'


[params]
  archives = { enabled = true }

[menu]
  [[menu.main]]
    name = "前端"
    url = "/categories/前端/"
    weight = 1
  [[menu.main]]
    name = "后端"
    url = "/categories/后端/"
    weight = 2
  [[menu.main]]
    name = "归档"
    url = "/archive/"
    weight = 3
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4
